privacy_setting: dp
evaluation: true
seeds: [0,1,2,3,4]
log_wandb: false

feature_extractor:
  name: scatternet
  J: 2
  L: 8
  m: 1

classifier:
  name: dp_cnn
  scale_norm: true
  batch_size: 128
  max_physical_batch_size: 4
  optimizer_name: nadam
  epochs: 10
  lr: 0.001
  
  epsilon: 1.0
  delta: 1e-4
  max_grad_norm: 1.2

defaults:
 - dataset: pppp
 - path: paths
 - _self_