privacy_setting: dp
evaluation: true

feature_extractor:
  name: scatternet
  J: 4
  L: 2
  m: 1

classifier:
  name: dp_linear
  epsilon: 1.0
  delta: 1e-4
  max_grad_norm: 1.2

  batch_size: 128
  max_physical_batch_size: 64
  optimizer_name: nadam
  epochs: 10
  lr: 0.01

seeds: [0,1,2,3,4]
log_wandb: true

defaults:
 - dataset: pppp
 - path: paths
 - _self_